### ISSUE TITLE
32bit version possible?

### ISSUE THREAD

**Issue by jose1711** [mtoensing/Moondance-StepMania64-pi4#1]
Hello, is there any hope for a 32bit version of this build? Thanks.

**Comment by mtoensing** [comment]
The 32 bit version is the normal version of Stepmania for Pi you can download on their page. But it will not run at full speed and is in my opinion unplayable. This is just the 64 bit binary of the fork of Stepmania called Moondance with my configuration and a setup script. But it will run at full speed. 

You can comple it from source https://github.com/stepmania/stepmania/releases or use Moondance 32-Bit https://projectmoon.dance/downloads. But on a Pi you don't want that.

**Comment by jose1711** [comment]
Thank you, I get that. But still.. is there any way of compiling Moondance on 32bit Raspbian and providing those binaries?

**Comment by mtoensing** [comment]
I did not compile anything. You will find the binaries for 32 and 64 bit here. I just copied the 64 bit version in this repository toi make my script more solid so that it only copies stuff you can find here. 

32 and 64 bit versions are here: https://projectmoon.dance/downloads 

But: 32 is too slow on a Pi4.

**Comment by jose1711** [comment]
Oh, OK. Thanks for explanation. TBH I did not check what your script was doing. I find it really interesting that 32bit version is that much slower than 64bit..

**Comment by mtoensing** [comment]
try it for yourself ;-)
